### ISSUE TITLE
Installation fails on GNU/Linux

### ISSUE THREAD

**Issue by iembry** [eddelbuettel/ttdo#1]
Hi, I have tried on a few occasions to install `ttdo` without success.

Below are the installation results:
 
    * installing *source* package ‘ttdo’ ...
    ** package ‘ttdo’ successfully unpacked and MD5 sums checked
    ** using staged installation
    ** R
    ** demo
    ** inst
    ** byte-compile and prepare package for lazy loading
    ** help
    *** installing help indices
    ** building package indices
    ** testing if installed package can be loaded from temporary location
    Error: package or namespace load failed for ‘ttdo’:
     .onLoad failed in loadNamespace() for 'ttdo', details:
      call: NULL
      error: 'register_tinytest_extension' is not an exported object from 'namespace:tinytest'
    Error: loading failed
    Execution halted
    ERROR: loading failed
    * removing ‘/library/ttdo’

**Comment by eddelbuettel** [comment]
Please do this:  `Rscript -e 'print(packageVersion("tinytest"))'`.

I get: 

```sh
edd@rob:~$ Rscript -e 'print(packageVersion("tinytest"))'
[1] ‘1.1.0’
edd@rob:~$ 
```

You may have an older version hiding somewhere.

**Comment by iembry** [comment]
~$ Rscript -e 'print(packageVersion("tinytest"))'
[1] ‘1.1.0’

**Comment by eddelbuettel** [comment]
It must be local to you because CRAN _really_ would come after me if there was something.

For argument's sake, a fresh install of both, straight at my bash prompt:

```sh
edd@rob:~$ install.r tinytest ttdo  # install.r from littler, installs from CRAN
trying URL 'https://cloud.r-project.org/src/contrib/tinytest_1.1.0.tar.gz'
Content type 'application/x-gzip' length 424395 bytes (414 KB)
==================================================
downloaded 414 KB

trying URL 'https://cloud.r-project.org/src/contrib/ttdo_0.0.3.tar.gz'
Content type 'application/x-gzip' length 4022 bytes
==================================================
downloaded 4022 bytes

begin installing package ‘tinytest’
* installing *source* package ‘tinytest’ ...
** package ‘tinytest’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (tinytest)
begin installing package ‘ttdo’
* installing *source* package ‘ttdo’ ...
** package ‘ttdo’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** demo
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (ttdo)

The downloaded source packages are in
	‘/tmp/downloaded_packages’
edd@rob:~$ 
```

PS  R 3.6.1, everything else current, Ubuntu 19.04 -- none of that should matter.

**Comment by iembry** [comment]
@eddelbuettel  Just so you know, I tried to install from CRAN again today & I was successful. Thank you.

**Comment by eddelbuettel** [comment]
Good! Any idea what the difference may have been?  [ Again, there is nothing form our end. Both are very minimal and simple packages.]
